version: '3'

volumes:
  mysql_data:
      driver: local

services:
  nginx:
    image: arunsingh/ms-nginx
    restart: unless-stopped
    container_name: "rs_nginx"
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./volumes/log/nginx:/var/log/nginx
      - ./volumes/www/development:/var/www
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot:/var/certbot
    links:
      - assets
      - mesh
      - search
        #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: "rs_certbot"
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mongodb:
    image: mongo:4.2
    container_name: "rs_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      #- MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      #- MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./volumes/data/db:/data/db
    ports:
      - 27019:27017
    command: mongod --bind_ip_all --logpath=/dev/null
  assets:
    image: arunsingh/ms-assets
    container_name: "rs_assets"
    environment:
      - spring.profiles.active=${spring_profiles_active}
      - JAVA_OPTS=-Xm2g -Xms2g
    ports:
      - "8100:8100"
      - "8042:8080"
    links:
      - mongodb
  mesh:
    image: arunsingh/ms-mesh
    container_name: "rs_mesh"
    environment:
      - spring.profiles.active=${spring_profiles_active}
      - SQUARE_APPLICATION_SECRET=${SQUARE_APPLICATION_SECRET}
      - SQUARE_APPLICATION_ID=${SQUARE_APPLICATION_ID}
      - SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID}
      - SQUARE_ACCESS_TOKEN=${SQUARE_ACCESS_TOKEN}
      - SQUARE_SM_APPLICATION_SECRET=${SQUARE_SM_APPLICATION_SECRET}
      - SQUARE_SM_APPLICATION_ID=${SQUARE_SM_APPLICATION_ID}
      - SQUARE_SM_LOCATION_ID=${SQUARE_SM_LOCATION_ID}
      - SQUARE_SM_ACCESS_TOKEN=${SQUARE_SM_ACCESS_TOKEN}
      - OPENNODE_API_KEY_SM=${OPENNODE_API_KEY_SM}
      - OPENNODE_API_KEY=${OPENNODE_API_KEY}
      - OPENNODE_ECOM_KEY=${OPENNODE_ECOM_KEY}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_ENV_VAR=${CLOUDINARY_ENV_VAR}
      - JAVA_OPTS=-Xm2g -Xms2g
    ports:
      - "8104:8104"
      - "8046:8080"
    links:
      - mongodb
  search:
    image: arunsingh/ms-search
    container_name: "rs_search"
    volumes:
      - /var/index:/var/index
    environment:
      - spring.profiles.active=${spring_profiles_active}
      - JAVA_OPTS=-Xm2g -Xms2g
    ports:
      - "8106:8106"
      - "8048:8080"
    links:
      - mongodb
  