name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image 
      run: cd nginx && docker build . --file Dockerfile --tag arunsingh/ms-nginx:latest 
    - name: Docker Login  
      username: arunsingh
      password: f17d4b70-4bfe-4c15-95fd-f622ffdfabfb
    - name: Build the Docker image 
      run:  docker push arunsingh/ms-nginx:latest   
      
